"""Predefined pipeline strategies and automatic selection.

A strategy is simply a list of ``BaseStep`` subclasses that the
``StepRunner`` instantiates and executes in order.  Three strategies
are predefined:

- **SINGLE_SHOT**: for stories under 2 000 words.
  Steps: ConceptStep → SingleShotStep → CleanStep → EvaluateStep
  No outline is generated. The LLM writes the full story in one pass
  directly from the Story Bible.

- **TWO_PASS**: for stories between 2 001 and 4 000 words.
  Steps: ConceptStep → OutlineStep → SingleShotStep → CleanStep → EvaluateStep
  An outline is generated first and injected as context into
  SingleShotStep so the LLM has structural guidance for a medium-length
  story without the overhead of section-by-section generation.
  The outline is consumed by SingleShotStep — not by SectionStep.

- **FULL_PIPELINE**: for stories over 4 000 words.
  Steps: ConceptStep → OutlineStep → SectionStep → StitchStep →
         CleanStep → EvaluateStep
  Sections are generated independently following the outline, then
  stitched together.  This is necessary for long texts that exceed
  a single LLM context window's practical output limit.

Adding a new strategy = registering a new factory function in
``_STRATEGY_REGISTRY``.  The ``StepRunner`` never needs to change.

Typical usage::

    name, steps = select_strategy(3000, settings)
    state = await runner.execute(state, steps)
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING, Callable

from core.steps.base_step import BaseStep

if TYPE_CHECKING:
    from core.settings import Settings

logger = logging.getLogger(__name__)

# ── Default word-count thresholds ────────────────────────────────────────────
# These are used when no Settings object is provided.  The canonical values
# live in settings.yaml under strategy.single_shot_max / strategy.two_pass_max.

DEFAULT_SINGLE_SHOT_MAX: int = 2000
DEFAULT_TWO_PASS_MAX: int = 4000


# ── Private step-list factories ───────────────────────────────────────────────


def _get_single_shot_steps() -> list[type[BaseStep]]:
    """Return the step list for the single-shot strategy.

    No outline is produced.  The Story Bible is passed directly to
    SingleShotStep, which writes the entire story in one LLM call.
    Appropriate for stories up to 2 000 words.
    """
    from core.steps.clean_step import CleanStep
    from core.steps.concept_step import ConceptStep
    from core.steps.evaluate_step import EvaluateStep
    from core.steps.single_shot_step import SingleShotStep

    return [
        ConceptStep,
        SingleShotStep,
        CleanStep,
        EvaluateStep,
    ]


def _get_two_pass_steps() -> list[type[BaseStep]]:
    """Return the step list for the two-pass strategy.

    An outline is generated first (OutlineStep), then injected as
    context into SingleShotStep so the LLM has structural guidance
    while still writing the full story in a single generation call.

    This is distinct from the full pipeline: SectionStep and StitchStep
    are NOT used here.  The outline is context for SingleShotStep, not
    a driver for section-by-section generation.  For 2 001-4 000 word
    stories, a single well-guided LLM call is more efficient and
    produces better narrative flow than independently generated sections.
    """
    from core.steps.clean_step import CleanStep
    from core.steps.concept_step import ConceptStep
    from core.steps.evaluate_step import EvaluateStep
    from core.steps.outline_step import OutlineStep
    from core.steps.single_shot_step import SingleShotStep

    return [
        ConceptStep,
        OutlineStep,
        SingleShotStep,
        CleanStep,
        EvaluateStep,
    ]


def _get_full_pipeline_steps() -> list[type[BaseStep]]:
    """Return the step list for the full pipeline strategy.

    The outline is generated by OutlineStep and then consumed by
    SectionStep, which generates each section independently.
    StitchStep combines the sections into a single coherent draft.
    Required for stories over 4 000 words where a single LLM call
    cannot reliably produce the full text at the required quality.
    """
    from core.steps.clean_step import CleanStep
    from core.steps.concept_step import ConceptStep
    from core.steps.evaluate_step import EvaluateStep
    from core.steps.outline_step import OutlineStep
    from core.steps.section_step import SectionStep
    from core.steps.stitch_step import StitchStep

    return [
        ConceptStep,
        OutlineStep,
        SectionStep,
        StitchStep,
        CleanStep,
        EvaluateStep,
    ]


# ── Strategy name constants ───────────────────────────────────────────────────

SINGLE_SHOT_STRATEGY_NAME: str = "single_shot"
TWO_PASS_STRATEGY_NAME: str = "two_pass"
FULL_PIPELINE_STRATEGY_NAME: str = "full_pipeline"

# ── Strategy registry ─────────────────────────────────────────────────────────
# Maps strategy name → callable that returns the step list.
# Add new strategies here without touching any other module.

_STRATEGY_REGISTRY: dict[str, Callable[[], list[type[BaseStep]]]] = {
    SINGLE_SHOT_STRATEGY_NAME: _get_single_shot_steps,
    TWO_PASS_STRATEGY_NAME: _get_two_pass_steps,
    FULL_PIPELINE_STRATEGY_NAME: _get_full_pipeline_steps,
}


# ── Public API ────────────────────────────────────────────────────────────────


def get_strategy(name: str) -> list[type[BaseStep]]:
    """Return the step list for a named strategy.

    Args:
        name: Strategy name (``"single_shot"``, ``"two_pass"``, or
            ``"full_pipeline"``).

    Returns:
        An ordered list of ``BaseStep`` subclasses.

    Raises:
        ValueError: If the strategy name is unknown.
    """
    factory = _STRATEGY_REGISTRY.get(name)
    if factory is None:
        available = ", ".join(sorted(_STRATEGY_REGISTRY.keys()))
        raise ValueError(
            f"Unknown strategy '{name}'. Available: {available}"
        )
    return factory()


def select_strategy(
    target_words: int,
    settings: "Settings | None" = None,
) -> tuple[str, list[type[BaseStep]]]:
    """Auto-select a strategy based on target word count.

    Thresholds are read from ``settings.strategy`` if provided,
    otherwise the module-level defaults are used.

    Decision logic:
    - target_words <= single_shot_max  ->  single_shot
    - target_words <= two_pass_max     ->  two_pass
    - target_words >  two_pass_max     ->  full_pipeline

    Args:
        target_words: The target word count for the story.
        settings: Application settings (optional).

    Returns:
        A tuple of ``(strategy_name, step_list)``.
    """
    if settings is not None:
        single_max = settings.strategy.single_shot_max
        two_pass_max = settings.strategy.two_pass_max
    else:
        single_max = DEFAULT_SINGLE_SHOT_MAX
        two_pass_max = DEFAULT_TWO_PASS_MAX

    if target_words <= single_max:
        name = SINGLE_SHOT_STRATEGY_NAME
    elif target_words <= two_pass_max:
        name = TWO_PASS_STRATEGY_NAME
    else:
        name = FULL_PIPELINE_STRATEGY_NAME

    steps = get_strategy(name)
    logger.info(
        "Strategy selected: '%s' for %d words "
        "(thresholds: <=%d=single_shot, <=%d=two_pass, >%d=full_pipeline)",
        name,
        target_words,
        single_max,
        two_pass_max,
        two_pass_max,
    )
    return name, steps


def list_strategies() -> list[str]:
    """Return all available strategy names.

    Returns:
        Sorted list of registered strategy names.
    """
    return sorted(_STRATEGY_REGISTRY.keys())
