"""Parse the incident_database.txt into a clean YAML resource.

Two-step: (1) structural parse into fields, (2) light Ru→En cleanup of
narrative fields using a targeted phrase dictionary. Anything not
covered by the dictionary is left in Russian; the LLM planner reads it
fine either way, but the field is flagged so the user can
translate-in-place later.
"""

from __future__ import annotations

import re
from pathlib import Path

import yaml

SRC = "/tmp/claude-0/-home-user-Aviation/c68f14de-7510-5a03-bd3d-301311f47502/scratchpad/zip4/text/incident_database.txt"
OUT = "resources/aviation/incidents.yaml"


# Phrase dictionary — mostly aviation terms + connective tissue.
# Applied longest-first to avoid partial replacements.
RU_EN: dict[str, str] = {
    "погибших из": "fatalities of",
    "погибших": "fatalities",
    "выживших": "survivors",
    "серьёзных травм": "serious injuries",
    "серьёзных ранений": "serious injuries",
    "лёгких травм": "minor injuries",
    "при эвакуации": "during evacuation",
    "на борту": "onboard",
    "из ": "of ",
    "человек": "people",
    "экипаж": "crew",
    "экипажа": "crew",
    "экипажу": "crew",
    "капитан": "captain",
    "капитана": "captain",
    "капитаном": "the captain",
    "первый офицер": "first officer",
    "первого офицера": "the first officer",
    "первому офицеру": "the first officer",
    "стюардесса": "flight attendant",
    "стюардессы": "flight attendants",
    "бортпроводник": "cabin crew",
    "бортпроводника": "cabin crew",
    "бортпроводники": "cabin crew",
    "пассажир": "passenger",
    "пассажиры": "passengers",
    "пассажиров": "passengers",
    "самолёт": "aircraft",
    "самолёта": "aircraft",
    "самолёту": "aircraft",
    "самолётом": "aircraft",
    "самолёте": "aircraft",
    "борт": "airframe",
    "борта": "airframe",
    "двигатель": "engine",
    "двигателя": "engine",
    "двигатели": "engines",
    "двигателей": "engines",
    "двух": "two",
    "трёх": "three",
    "четырёх": "four",
    "оба": "both",
    "обоих": "both",
    "все": "all",
    "всех": "all",
    "полёт": "flight",
    "полёта": "flight",
    "полёте": "flight",
    "полосе": "runway",
    "полосу": "runway",
    "посадка": "landing",
    "посадку": "landing",
    "посадки": "landing",
    "посадочной": "landing",
    "взлёт": "takeoff",
    "взлёта": "takeoff",
    "после взлёта": "after takeoff",
    "перед взлётом": "before takeoff",
    "минут": "min",
    "минуты": "min",
    "минуту": "minute",
    "секунд": "sec",
    "часов": "h",
    "часа": "h",
    "час": "h",
    "года": "years",
    "лет": "years",
    "лёт": "yrs",
    "фут": "ft",
    "футов": "ft",
    "футах": "ft",
    "миль": "mi",
    "миля": "mi",
    "километр": "km",
    "километра": "km",
    "километров": "km",
    "узлов": "kt",
    "узла": "kt",
    "тонн": "t",
    "нашли": "were found",
    "нашли живым": "was found alive",
    "нашёл": "found",
    "спас": "saved",
    "спасли": "rescued",
    "убил": "killed",
    "погиб": "died",
    "умер": "died",
    "выжил": "survived",
    "смог": "was able to",
    "смогла": "was able to",
    "успел": "managed to",
    "поднял": "raised",
    "показал": "showed",
    "сказал": "said",
    "сказала": "said",
    "сообщил": "reported",
    "сообщила": "reported",
    "заявил": "stated",
    "случилось": "happened",
    "случай": "case",
    "случая": "case",
    "инцидент": "incident",
    "инцидента": "incident",
    "инциденте": "the incident",
    "инцидентов": "incidents",
    "катастрофа": "disaster",
    "катастрофы": "the disaster",
    "катастрофу": "the disaster",
    "расследование": "investigation",
    "расследования": "the investigation",
    "проверка": "inspection",
    "техническая проверка": "technical inspection",
    "проверки": "inspection",
    "отказ": "failure",
    "отказа": "failure",
    "отказали": "failed",
    "отказал": "failed",
    "отказала": "failed",
    "перезапустился": "restarted",
    "перезапустил": "restarted",
    "перезапустились": "restarted",
    "перезапустить": "restart",
    "отключил": "shut down",
    "отключился": "shut down",
    "отключилась": "shut down",
    "лопнули": "burst",
    "лопнул": "burst",
    "разорвался": "ruptured",
    "разорвался диск": "disc ruptured",
    "лобовое стекло": "windshield",
    "лобового стекла": "the windshield",
    "гидросистем": "hydraulic systems",
    "гидросистемы": "hydraulic systems",
    "гидравлического": "hydraulic",
    "гидравлика": "hydraulics",
    "штопор": "spin",
    "штопора": "spin",
    "шпоров": "spin",
    "штопоре": "in a spin",
    "штопор на малой высоте": "low-altitude spin",
    "штурвал": "control column",
    "рычаг": "lever",
    "рычаги": "levers",
    "закрылки": "flaps",
    "предкрылки": "slats",
    "триммер": "trim",
    "автопилот": "autopilot",
    "автопилоту": "the autopilot",
    "автопилота": "the autopilot",
    "автотяга": "autothrottle",
    "автотяги": "autothrottle",
    "тяги": "thrust",
    "тяга": "thrust",
    "без тяги": "without thrust",
    "стойка": "gear leg",
    "шасси": "landing gear",
    "передняя стойка": "nose gear",
    "основная стойка": "main gear",
    "предполётной проверке": "pre-flight inspection",
    "проверке": "inspection",
    "гроза": "thunderstorm",
    "грозы": "thunderstorm",
    "грозой": "the thunderstorm",
    "град": "hail",
    "града": "hail",
    "ветер": "wind",
    "ветра": "wind",
    "молния": "lightning",
    "молнии": "lightning",
    "обледенение": "icing",
    "обледенения": "icing",
    "обледенении": "icing",
    "погоды": "weather",
    "погода": "weather",
    "тумане": "in fog",
    "туман": "fog",
    "пепел": "ash",
    "пепла": "ash",
    "вулканический": "volcanic",
    "вулкан": "volcano",
    "вулкана": "volcano",
    "заправке": "refueling",
    "заправки": "refueling",
    "топливо": "fuel",
    "топлива": "fuel",
    "керосин": "kerosene",
    "утечка": "leak",
    "утечки": "leaks",
    "утечку": "the leak",
    "напутали": "confused",
    "перепутали": "confused",
    "разминулись": "missed each other",
    "перепад давления": "pressure differential",
    "разгерметизация": "decompression",
    "разгерметизации": "decompression",
    "декомпрессии": "decompression",
    "рейс": "flight",
    "рейса": "flight",
    "рейсу": "the flight",
    "аэропорт": "airport",
    "аэропорта": "the airport",
    "аэропорту": "the airport",
    "аэродром": "airfield",
    "аэродрома": "the airfield",
    "аэродромов": "airfields",
    "аэродрому": "the airfield",
    "аэродроме": "the airfield",
    "полосой": "runway",
    "лётной полосе": "runway",
    "маршрут": "route",
    "маршрута": "route",
    "маршруту": "the route",
    "маршруте": "the route",
    "заходил": "was on approach",
    "заходили": "were on approach",
    "заход": "approach",
    "захода": "approach",
    "приземлился": "touched down",
    "приземлились": "touched down",
    "приземлилась": "touched down",
    "коснулся": "touched",
    "приземления": "landing",
    "касания": "touchdown",
    "касание": "touchdown",
    "остановился": "stopped",
    "остановилась": "stopped",
    "остановились": "stopped",
    "потерял": "lost",
    "потеряла": "lost",
    "потеряли": "lost",
    "поднялся": "climbed",
    "поднялась": "climbed",
    "поднялись": "climbed",
    "снижался": "descended",
    "снижались": "descended",
    "снижение": "descent",
    "снижения": "descent",
    "снижении": "the descent",
    "падение": "drop",
    "падал": "was falling",
    "падала": "was falling",
    "падали": "were falling",
    "упал": "fell",
    "упала": "fell",
    "упали": "fell",
    "врезался": "struck",
    "врезалась": "struck",
    "врезались": "struck",
    "разбился": "crashed",
    "разбилась": "crashed",
    "столкнулся": "collided",
    "столкновение": "collision",
    "столкновения": "the collision",
    "с воздухом": "in mid-air",
    "с землёй": "with terrain",
    "нос": "nose",
    "хвост": "tail",
    "крыло": "wing",
    "крыла": "wing",
    "фюзеляж": "fuselage",
    "фюзеляжа": "fuselage",
    "фюзеляжу": "fuselage",
    "лопасть": "blade",
    "лопасти": "blades",
    "лопаток": "blades",
    "вентиляторный диск": "fan disc",
    "нос стойка": "nose gear",
    "уconтained failure": "uncontained failure",
    "предупреждал": "had warned",
    "предупреждала": "had warned",
    "предупредили": "warned",
    "не услышанный": "unheard",
    "нёс": "was carrying",
    "везли": "were carrying",
    "везла": "was carrying",
    "войны": "the war",
    "войну": "the war",
    "войне": "the war",
    "гражданской войне": "civil war",
    "мировой войне": "world war",
    "во всём мире": "worldwide",
    "было принято": "was adopted",
    "было изменено": "was changed",
    "изменил": "changed",
    "изменили": "changed",
    "изменения": "changes",
    "правила": "regulations",
    "стандарты": "standards",
    "стандарт": "standard",
    "регламент": "regulation",
    "регламенты": "regulations",
    "Инцидент переписал стандарты": "The incident rewrote the standards",
    "Тот же борт": "The same airframe",
    "летал": "flew",
    "летал ещё": "went on to fly",
    "летали": "flew",
    "продан": "sold",
    "продана": "sold",
    "пенсию": "retirement",
    "на пенсии": "in retirement",
    "ушёл на пенсию": "was retired",
    "ушёл на слом": "was scrapped",
    "прошли": "went",
    "прошёл": "went",
    "прошла": "went",
    "около": "about",
    "приблизительно": "approximately",
    "неизвестен": "unknown",
    "неизвестна": "unknown",
    "неизвестно": "unknown",
    "недалеко": "not far",
    "рядом": "nearby",
    "также": "also",
    "именно": "specifically",
    "затем": "then",
    "потом": "then",
    "снова": "again",
    "снова заглох": "flamed out again",
    "заглох": "flamed out",
    "заглохли": "flamed out",
    "загорелся": "caught fire",
    "загорелась": "caught fire",
    "пожар": "fire",
    "пожара": "fire",
    "пожаром": "the fire",
    "дым": "smoke",
    "дыма": "smoke",
    "пропал": "went missing",
    "пропала": "went missing",
    "пропали": "went missing",
    "исчез": "disappeared",
    "исчезла": "disappeared",
    "нашли обломки": "the wreckage was found",
    "обломки": "wreckage",
    "обломков": "wreckage",
    "черный ящик": "black box",
    "чёрный ящик": "black box",
    "чёрного ящика": "the black box",
    "переговоры": "communications",
    "переговорах": "communications",
    "радиопереговоров": "radio communications",
    "радиосвязи": "radio contact",
    "радиосвязь": "radio contact",
    "командир": "captain",
    "команду": "crew",
    "с точки зрения": "from the perspective of",
    "точку зрения": "perspective",
    "имя": "name",
    "жизнь": "life",
    "жизнью": "life",
    "жизней": "lives",
    "жизни": "lives",
    "гибели": "of death",
    "смерти": "of death",
    "выжившие": "the survivors",
    "выжившим": "the survivors",
    "оценили": "assessed",
    "оценил": "assessed",
    "оценка": "assessment",
    "разбор": "analysis",
    "показания": "testimony",
    "показал что": "showed that",
    "показала что": "showed that",
    "оба": "both",
    "оба самолёта": "both aircraft",
    "весь": "the entire",
    "всё": "everything",
    "вся": "the entire",
    "например": "for example",
    "вопреки": "despite",
    "благодаря": "thanks to",
    "который": "which",
    "которая": "which",
    "которое": "which",
    "которого": "which",
    "которой": "which",
    "потому что": "because",
    "потому": "because",
    "поэтому": "therefore",
    "если": "if",
    "если бы": "if",
    "тогда": "then",
    "когда": "when",
    "пока": "while",
    "уже": "already",
    "ещё": "still",
    "только": "only",
    "иногда": "sometimes",
    "часто": "often",
    "редко": "rarely",
    "почти": "almost",
    "полностью": "completely",
    "частично": "partially",
    "полностью потерял": "completely lost",
    "почти новый": "nearly new",
    "новый": "new",
    "новая": "new",
    "новое": "new",
    "старый": "old",
    "старая": "old",
    "старое": "old",
    "первый": "first",
    "второй": "second",
    "третий": "third",
    "последний": "last",
    "последняя": "last",
    "последнего": "the last",
    "первого": "the first",
    "спокойный": "calm",
    "тихий": "quiet",
    "громкий": "loud",
    "медленный": "slow",
    "быстрый": "fast",
    "долгий": "long",
    "короткий": "short",
    "самое": "the most",
    "самый": "the most",
    "самая": "the most",
    "легенда": "legend",
    "легендарный": "legendary",
    "легендарное": "legendary",
    "легендарная": "legendary",
    "мировой рекорд": "world record",
    "успешная": "successful",
    "успешное": "successful",
    "успешный": "successful",
    "неудачный": "unsuccessful",
    "неудачная": "unsuccessful",
    "неудачное": "unsuccessful",
    "и": "and",
    "или": "or",
    "но": "but",
    "по": "along",
    "как": "as",
    "что": "that",
    "чтобы": "so that",
    "также важно": "also important",
    "около": "about",
}


def rulite_translate(text: str) -> str:
    """Best-effort Russian → English via a fixed phrase dictionary.

    Anything not covered stays in Russian. Long phrases are applied
    before short ones to avoid partial replacements.
    """
    if not text:
        return ""
    # Sort keys by length desc so we replace long phrases first.
    for ru in sorted(RU_EN.keys(), key=len, reverse=True):
        text = re.sub(rf"(?i)\b{re.escape(ru)}\b", RU_EN[ru], text)
    # Clean up cyrillic-latin adjacency artifacts.
    text = re.sub(r"\s+", " ", text).strip()
    return text


def has_cyrillic(text: str) -> bool:
    return bool(re.search(r"[а-яА-ЯёЁ]", text or ""))


def parse() -> list[dict]:
    text = Path(SRC).read_text(encoding="utf-8")
    incidents: list[dict] = []
    section = ""
    # Split at each INCIDENT: header.
    chunks = re.split(r"\n(?=INCIDENT:\s)", text)
    for chunk in chunks:
        sec_m = re.search(r"^РАЗДЕЛ\s+\d+\s+—\s+(.+)$", chunk, re.M)
        if sec_m:
            section = sec_m.group(1).strip()
        if not chunk.startswith("INCIDENT:"):
            continue
        name = re.match(r"INCIDENT:\s*(.+?)$", chunk, re.M).group(1).strip()

        def pick(key: str) -> str:
            m = re.search(rf"^{re.escape(key)}:\s*(.+?)$", chunk, re.M)
            return m.group(1).strip() if m else ""

        # KEY DRAMATIC DETAILS block until CATEGORIZED / SOURCES.
        dramatic: list[str] = []
        m = re.search(r"^KEY DRAMATIC DETAILS:\s*$", chunk, re.M)
        if m:
            rest = chunk[m.end():]
            stop = re.search(r"^(?:CATEGORIZED BY MY AXES[^\n]*|SOURCES):", rest, re.M)
            body = rest[: stop.start()] if stop else rest
            dramatic = [ln.strip() for ln in body.strip().splitlines() if ln.strip()]

        # SOURCES.
        sources: list[str] = []
        m = re.search(r"^SOURCES:\s*$", chunk, re.M)
        if m:
            rest = chunk[m.end():]
            body = rest.split("\n\n", 1)[0]
            sources = [ln.strip() for ln in body.strip().splitlines() if ln.strip()]

        raw = {
            "name": name,
            "section": section,
            "date": pick("Date"),
            "aircraft": pick("Aircraft"),
            "location": pick("Location"),
            "failure_type": pick("Type of failure"),
            "outcome": pick("Outcome"),
            "casualties": pick("Casualties"),
            "dramatic_details": dramatic,
            "sub_genre_primary": pick("Sub-genre (Layer 2, primary)"),
            "sub_genre_secondary": pick("Sub-genre (secondary)"),
            "causation_type": pick("Causation type"),
            "aircraft_type": pick("Aircraft type (Layer 2)"),
            "setting_layer2": pick("Setting (Layer 2 ОСЬ 4)"),
            "setting_geographic": pick("Setting (geographic)"),
            "monetization_risk": pick("Monetization risk"),
            "twist_potential": pick("Twist potential"),
            "sources": sources,
        }
        # Translate narrative fields.
        translated = dict(raw)
        for k in ("failure_type", "outcome", "casualties", "twist_potential", "setting_layer2"):
            translated[k] = rulite_translate(raw[k])
        translated["dramatic_details"] = [rulite_translate(d) for d in raw["dramatic_details"]]
        # If cyrillic remains, mark for follow-up translation.
        needs_translation = any(
            has_cyrillic(translated[k]) for k in ("failure_type", "outcome", "casualties", "twist_potential")
        ) or any(has_cyrillic(d) for d in translated["dramatic_details"])
        translated["translation_status"] = "partial" if needs_translation else "clean"
        incidents.append(translated)
    return incidents


def main() -> None:
    incidents = parse()
    Path("resources/aviation").mkdir(parents=True, exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        yaml.safe_dump(
            {"incidents": incidents},
            f,
            allow_unicode=True,
            sort_keys=False,
            width=200,
        )
    n_partial = sum(1 for i in incidents if i["translation_status"] == "partial")
    print(f"Wrote {len(incidents)} incidents. Translation status: {len(incidents) - n_partial} clean / {n_partial} partial.")


if __name__ == "__main__":
    main()
